spring.application.name=design-patterns

# Habilita o painel do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configura??o da URL do banco de dados em mem?ria
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Desabilita o redirecionamento padrão para o Petstore do Swagger
springdoc.swagger-ui.disable-swagger-default-url=true

# (Opcional) Define o caminho onde você acessará o Swagger
springdoc.swagger-ui.path=/swagger-ui.html